# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8351bd5ebda503a4b51e31136af5e14ce80af3886de9b6aa395ccb996d35403dab9b8f4a2c94171888e9c71c472a56d5bf6c796036100d1b51355ba8a45e7d9d

test:
  secret_key_base: c342c5958207e81a7242d07c11cbb6051608993f43dfe6aeab0828a20b5f11f0608165a82fc13a13525eb43ba2a67c8360578325b12228159505f21b853b521e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
